export const POST_LOAD_SUCCESS = 'POST_LOAD_SUCCESS';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_LOADING = 'POST_DELETE_LOADING';

export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS';
export const POST_ADD_LOADING = 'POST_ADD_LOADING';

export const SHOW_CURRENT_POST_LOADING = 'SHOW_CURRENT_POST_LOADING';
export const SHOW_CURRENT_POST_SUCCESS = 'SHOW_CURRENT_POST_SUCCESS';
